### ISSUE TITLE
Decoupling / Deregistering

### ISSUE THREAD

**Issue by bryan** [xiaolin/react-image-gallery#136]
I'm getting a warning when going back a page before the component is fully loaded, and it presents me with this error message. Is there anyway I can unregister the `ImageGallery` when the main componentWillUnmount so that I can prevent this error? 

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ImageGallery component.`

**Comment by xiaolin** [comment]
How can I replicate this? Are you sure `ImageGallery` is being removed after you unmount your component?

**Comment by bryan** [comment]
It's hard to replicate since I'm using a full fledged project with routers. The problem is: when I go back a page, my project's router trigger the redirect in the next event loop/tick, so the ImageGallery component still renders, and then the redirect happens, so setState from ImageGallery is still called while being unmounted. I may need a way to stop setState if the current page is going to be unmounted. https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html is a read on what's happening.

**Comment by willrp** [comment]
This issue still happens to me. I'm using react-router too, and react-image-gallery 0.8.7. 
The warning is displayed only when I hit back, hence unmounting the parent component where the image-gallery is, while a transition is happening. I suppose that the image-gallery parent component triggers componentWillUnmount(), and, since a transition is happening, the state from the image-gallery is changing hence it's unmounted.
