### ISSUE TITLE
Jank when resizing

### ISSUE THREAD

**Issue by jcheroske** [xiaolin/react-image-gallery#158]
When resizing the window, the `handleResize` function is called with every window resize event. This is causing excessive delay in the screen refresh. The profiler is also showing too much time being spent in `handleResize` and its sub-functions. Putting a throttle of 500ms on the firing of `handleResize` fixed the problem.

**Comment by xiaolin** [comment]
Released in `v0.7.14`

**Comment by Arsolio** [comment]
Hello @xiaolin  . I'm using your module with [react-responsive](https://github.com/contra/react-responsive) . On big and small devices i'm using different components, that's why on resizing imageGallery can be unmounted. But on fast resize i get: 
"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ImageGallery component."
I think, it's because of setTimeout in handleResize.
