### ISSUE TITLE
Maybe a lazyload bug?

### ISSUE THREAD

**Issue by ShindouHikaru** [xiaolin/react-image-gallery#188]
If i scroll to 6th item, i think the 2nd,3rd,4th,5th items shouldn't be loaded, but i find it send request in chrome Dev Tools. And if can set preload count will be better, now is 1 item. :)

**Comment by xiaolin** [comment]
It can be further optimized, i'll label this as a feature, since the current behavior is intentional.

**Comment by xiaolin** [comment]
After looking into this, the current behavior is intentional. The current index is loaded along with the previous and the next. This way if you're swiping left or right you won't see a blank image. 

On initial load if you're on index 0, index 1(next slide) will load, along with index N (previous slide).
If you slide to the 6th item, index 5 and index 7 will load to allow sliding left and right without blank images.

Closing this.

**Comment by ShindouHikaru** [comment]
Yes, you're right, my wrong, i just tested it, if i click index 11, just loaded 10, 11, 12.  Sorry for my miss
