### ISSUE TITLE
Strange initial animation when startIndex is set

### ISSUE THREAD

**Issue by Vyprichenko** [xiaolin/react-image-gallery#196]
Hi!
I've noticed a behavior that seems a bit strange for me: when ImageGallery is rendered with startIndex > 0 it animates thumbnails container positioning it initially to start with active thumbnail, then moves it back to thumbnail #0.
Reproduction of this issue on the last version of react-image-gallery:
![image_gallery_startindex](https://cloud.githubusercontent.com/assets/15525203/26551003/22e8bd94-4489-11e7-99a7-ac119ef96967.gif)

**Comment by xiaolin** [comment]
I'm unable to reproduce I've tried chrome,firefox and safari. Both active thumbnail and slide are correct.
![screen capture on 2017-06-03 at 13-19-12](https://cloud.githubusercontent.com/assets/1286776/26755648/8a03017c-485f-11e7-938a-be3b10cc5b74.gif)

**Comment by Vyprichenko** [comment]
Thank you for your reply.
There is no problem with the thumbnail and slide number, I was talking about animation which appears when startIndex> 0: thumbnails bar is moving left, then goes back. I can see it on your record too.
In my case I have two galleries: one small built into page and one full screen (custom, not the same as yours). When user clicks on a small gallery, the full screen is rendered with appropriate startIndex. It works OK, but this left-right moving looks unnecessary.

I tried to illustrate it here:
![image_gallery_startindex](https://user-images.githubusercontent.com/15525203/27087022-9369217e-505c-11e7-803e-808d70ee7cab.gif)

**Comment by delacalera** [comment]
Hi @xiaolin ,
I've been doing a bit of research and have possible solution for this issue.
There's a conditional that must be extended in order to prevent this behaviour.
In line 640 need to change 

`if (this._thumbnails.scrollWidth <= thumbnailsWrapperWidth ) {`

For 

`if (this._thumbnails.scrollWidth <= thumbnailsWrapperWidth || thumbnailsWrapperWidth <= 0) {`

I've commited the source code with a couple TODO comments so you can take a look.
Also, reducing the resize delay from 500 to i.e. 50, will improve even more the behaviour.
I'll thank you very much to implement this solution in your next release.
Cheers!

**Comment by xiaolin** [comment]
This has been fixed.
