### ISSUE TITLE
Disable animation for image description

### ISSUE THREAD

**Issue by vugman** [xiaolin/react-image-gallery#207]
Is it possible to disable the description being part of the slide animation?

**Comment by xiaolin** [comment]
What do you mean by that? The image description is attached to the slide, I'm not sure what it means to disable it.

**Comment by xiaolin** [comment]
Did you solve your issue? If so I'll close this soon.

**Comment by Gangezilla** [comment]
Hey @xiaolin, I'm trying to work on a fix for this at the moment. I think what @vugman means is that instead of having the description slide with the image, it would look something like this: 
![no-slide](https://user-images.githubusercontent.com/8536243/28400908-92a24bd4-6d59-11e7-9f9c-2f2ac33b563a.gif)

instead of looking like this: 
![slide](https://user-images.githubusercontent.com/8536243/28400925-ab23589c-6d59-11e7-891d-caa0015e3350.gif)

The reason I wanted to do this is that for our use case, our text sits on the left of the container, and when moving between images, the text travels across the whole screen to get back to where it needs to be, like so:
![gallery](https://user-images.githubusercontent.com/8536243/28400969-025f5f66-6d5a-11e7-86b3-c915df12a5b1.gif)

I'm attempting to solve this by having an additional prop that will cause the text to be rendered outside of the image container, like the first image up above. 

However, this causes duplicate descriptions to appear when a user chooses to render the description in a custom render function, such as in the app.js `_renderVideo` function. Did you have any advice on the best way to approach this? I can't think of a way to resolve this without changing how the `renderItem` function would work. 

Thanks!

**Comment by xiaolin** [comment]
If I'm understanding right, you want the ability to have one standard text for the entire gallery?

If so you should be able to position an absolute element outside the gallery.

```html
<div style={{position: 'relative'}}>
  <ImageGallery>
  <span style={{position: 'absolute', bottom: '0', left: '0'}}>Some absolutely position text<span>
</div>
```
