### ISSUE TITLE
Disable fullscreen icon on special items?

### ISSUE THREAD

**Issue by jansohn** [xiaolin/react-image-gallery#298]
I'd like to not show the fullscreen icon if showing for example a video slide (as the embedded video has its own controls). But I'd still like to show the fullscreen icon for standard images. Is this possible?

**Comment by xiaolin** [comment]
Take a look at the demo page and [demo file](https://github.com/xiaolin/react-image-gallery/blob/master/example/app.js). I added a layer on top of the video so that I can toggle on and off the fullscreen icon. 

You can also adjust the state `showFullscreenButton` when you're on a video slide. You'll need to add logic in your component to detect if its a video slide or not.
