### ISSUE TITLE
How to handle too many bullets?

### ISSUE THREAD

**Issue by tamasPetki** [xiaolin/react-image-gallery#414]
<img width="1274" alt="Képernyőfotó 2019-05-09 - 9 46 49" src="https://user-images.githubusercontent.com/35768535/57436195-80beba00-723f-11e9-8108-c32c92fcfe72.png">

Hi!

Can you please help how to solve this issue? Many thanks in advance!

**Comment by xiaolin** [comment]
It seems you modified the CSS to not wrap? By default, they should wrap.

I suggest for slides with that many bullets, it may be better to use the prop `showIndex` instead of rendering all the image bullets. If you must you'll have to wrap the bullets and use CSS to create enough space between them.

**Comment by tamasPetki** [comment]
Thanks for your quick suggestion :)
