### ISSUE TITLE
display problems when all images are not the same orientation 

### ISSUE THREAD

**Issue by rodnolan** [xiaolin/react-image-gallery#456]
Everything looks and behaves nicely when all of the images are in landscape mode (like in the demo) but if just one image is in portrait mode, that image is truncated in fullscreen mode and the thumbnails slider is displayed with a lot of white space above and below the landscape thumbnails.

To see this in action, you can use the batch of images at: [https://rodnolan.github.io/react-image-gallery-demo/](https://rodnolan.github.io/react-image-gallery-demo/) where two of the images are rotated 90 degrees to portrait mode.

Ideally, the height of all images, both portrait and landscape, should be constrained to the same value in both the thumbnails track and in fullscreen mode. And, in the thumbnail track, there should be no whitespace around adjacent images in the opposite orientation.  

I'm working on a solution for this that involves a server-side API to provide width and height information for each image but it would be great if this could be handled completely by the component. Do you think this is possible?

**Comment by xiaolin** [comment]
I purposely left this solution up to the user to solve. Ideally, you would create a gallery with all the same width/height image so the experience is better. But if you must have images with different height and width, you'll have to modify the CSS to fit your needs. Its quite tricky to calculate the proper CSS to fit all image sizes because you may have some images that are extra wide, and some images that are extra tall. If they both exist in the gallery it becomes hard to prioritize how the gallery should handle both images (whether to restrict the container by height or restrict the container by width). This is especially hard without knowing the image height/width ahead of time. 

Hopefully, this makes sense, please see previous issues for more info on some possible solutions
https://github.com/xiaolin/react-image-gallery/issues/113
https://github.com/xiaolin/react-image-gallery/issues/48
https://github.com/xiaolin/react-image-gallery/issues/339

**Comment by bogdanGS** [comment]
You can give the hight of image depending the class of parent element. So, when it is not in fullscreen, it will be the same height in landscape and portrait mode. If it is in fullscreen you can give it a height and if it is not, give it another height. You can play around with heights to fit to you design, but in my project, the code below fits as I expected.
.image-gallery-content img {
  height: 37rem;
}
.fullscreen img {
  height: 85vh;
}
.image-gallery-thumbnail img {
  width: auto;
  height: 75px;
}
