### ISSUE TITLE
can not load image-gallery.css

### ISSUE THREAD

**Issue by whupanglong** [xiaolin/react-image-gallery#47]
how? 
import react-image-gallery like the instruction, but no css loaded, I found those in file image-gallery.css

**Comment by xiaolin** [comment]
If you are using scss, then you can use the import feature 
`@import "../node_modules/react-image-gallery/src/ImageGallery";`

otherwise if you are using css, you can just copy paste the contents of image-gallery.css  located in `node_modules/react-image-gallery/build/image-gallery.css `into your project directory and include it in your index.html. 
`<link rel="stylesheet" href="myproject/css/image-gallery.css" />`

**Comment by xiaolin** [comment]
I will mark this as closed, feel free to open if you have any other questions
