### ISSUE TITLE
Consider reducing the size of this module

### ISSUE THREAD

**Issue by OZZlE** [xiaolin/react-image-gallery#501]
It's 52.5 KB https://bundlephobia.com/result?p=react-image-gallery@1.0.7

I see that you use lodash for example, have you considered using the smaller `lodash-es`? https://www.npmjs.com/package/lodash-es

**Comment by DJCMBear** [comment]
Using lodash-es for a couple of modules tends to not be required and could sometimes cause the size to increase instead of decrease, for example if you have a look at the data set in the link below you'll see with three modules from lodash like this component does, it shows a smaller footprint by using 'lodash.utility' imports over 'lodash-es' to import them, I would agree if there were more modules being imported this would be a viable option to reduce bundle size however I am not sure if this is required.

https://gist.github.com/chardos/a5791462e01e8e5ad2f9918c09408518#file-lodash-csv

N.B. A better solution to reduce the bundle size is to convert the component to utilise hooks and expand the source to smaller files, for example instead of having one 1,500+ line file, the component is separated out into smaller files each handling it's own part of the whole, maybe also use the context api so the component has it's own state manager so duplicate code is reduced.

**Comment by xiaolin** [comment]
Hmm, I'll have to look into this when I get some time. It seems the recent changes with `lodash` isEqual added more than I imagine!

I'm not sure how smaller files will help reduce bundle size, Id imagine everything be brought together during the bundle anyway.
I'm all about splitting source into smaller files for large projects. For small package components like this It is much easier to navigate a single file since everything is so tightly coupled.

**Comment by AustinLeeGordon** [comment]
Found [this article](https://formidable.com/blog/2018/introducing-react-fast-compare/) from Formidable Labs about [`react-fast-compare`](https://github.com/FormidableLabs/react-fast-compare). They wrote it to replace `lodash.isEqual`. Looks pretty promising—might be worth considering. It's 639 bytes gzipped according to [their README](https://github.com/FormidableLabs/react-fast-compare#readme).

@DJCMBear I agree on moving to functional components. Would eliminate a ton of bloat! Would require a major version change though since React would need to be version 16.8.

**Comment by OZZlE** [comment]
> Using lodash-es for a couple of modules tends to not be required and could sometimes cause the size to increase instead of decrease, for example if you have a look at the data set in the link below you'll see with three modules from lodash like this component does, it shows a smaller footprint by using 'lodash.utility' imports over 'lodash-es' to import them, I would agree if there were more modules being imported this would be a viable option to reduce bundle size however I am not sure if this is required.
> https://gist.github.com/chardos/a5791462e01e8e5ad2f9918c09408518#file-lodash-csv

It probably depends on which bundler you use also and I don't think the bundlers are so clever as most people may think: https://twitter.com/swyx/status/1195753642701144064

In our case we use Formik for forms which is pretty popular for React Forms and it already requires lodash-es so now we have both lodash and lodash-es because we use this as well..

> reduce the bundle size is to convert the component to utilise hooks 

I believe this would help also!

> and expand the source to smaller files, for example instead of having one 1,500+ line file, the component is separated out into smaller files each handling it's own part of the whole, maybe also use the context api so the component has it's own state manager so duplicate code is reduced.

If by doing this you can reduce duplicate code it will be true but it can also be the reverse in some cases, for example imports, in some cases I've seen the bundler duplicate Helper functions for each component. I saw a post on Twitter about it as well but I cannot find it now.

Here are the stats for our project for example (our source excluded - created with webpack-bundle-analyzer):
<img width="790" alt="Skärmklipp 2020-05-13 08 22 32" src="https://user-images.githubusercontent.com/893783/81779361-d97cfe80-94f4-11ea-997e-70a7b0daed11.png">
<img width="1031" alt="Skärmklipp 2020-05-13 08 23 01" src="https://user-images.githubusercontent.com/893783/81779371-dda91c00-94f4-11ea-8310-94a61d776398.png">

**Comment by xiaolin** [comment]
Using `react-fast-compare` and `lodash-es` in `1.2.2` and has helped reduce the bundle size a bit (~12%). Open to other suggestions, but will mark this as complete. 

```basg
asset image-gallery.js 46.5 KiB [compared for emit] [minimized] (name: main)
orphan modules 52.9 KiB [orphan] 19 modules
runtime modules 1.13 KiB 5 modules
built modules 133 KiB [built]
  modules by path ./node_modules/ 16.2 KiB
    modules by path ./node_modules/prop-types/ 2.58 KiB
      ./node_modules/prop-types/index.js 710 bytes [built] [code generated]
      ./node_modules/prop-types/factoryWithThrowingShims.js 1.58 KiB [built] [code generated]
      ./node_modules/prop-types/lib/ReactPropTypesSecret.js 314 bytes [built] [code generated]
    ./node_modules/react-fast-compare/index.js 4.32 KiB [built] [code generated]
    ./node_modules/react-swipeable/dist/react-swipeable.umd.js 9.29 KiB [built] [code generated]
  ./src/ImageGallery.js + 19 modules 117 KiB [built] [code generated]
  external {"commonjs":"react","commonjs2":"react","amd":"React","root":"React"} 42 bytes [built] [code generated]
webpack 5.44.0 compiled successfully in 7070 ms
```
