### ISSUE TITLE
 ReferenceError: document is not defined

### ISSUE THREAD

**Issue by sinkcup** [xiaolin/react-image-gallery#55]
```
npm run dev
```

> /home/ubuntu/code/demo/node_modules/screenfull/dist/screenfull.js:69
> 			if (val && val[1] in document) {
> 			                     ^
> 
> ReferenceError: document is not defined

**Comment by xiaolin** [comment]
This is odd, is this happening when you `import react-image-gallery`? Can you show more of the stack trace?

**Comment by xiaolin** [comment]
@sinkcup 
screenfull.js breaks server-side rendering, I will try to find some time to implement an isomorphic fullscreen solution

**Comment by keyeh** [comment]
+1 to isomorphic rendering

**Comment by sinkcup** [comment]
@xiaolin Thx! I am using fluxible server rending.

**Comment by chadoh** [comment]
In https://github.com/xiaolin/react-image-gallery/blob/master/src/ImageGallery.jsx#L150, you might be able to use `const ScreenFull = require('screenfull');` at the beginning of the `fullScreen()` function, rather than using `import` at the top level. Then `screenfull` will only be loaded one the user takes an action, which implies a browser environment.

**Comment by xiaolin** [comment]
v0.6.3 released and fixes server side rendering.

I ended up just using https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API and removing screenful.js. This should do for modern browsers.
