### ISSUE TITLE
Big issue: Not able to swipe the slides when any video is playing

### ISSUE THREAD

**Issue by SatyamKr07** [xiaolin/react-image-gallery#618]
Describe the bug
When we play a video (eg. From YouTube) , we are not able to swipe the slide. This becomes a big issue if we don't have the navigation button, thumbnail, bullets enabled to keep the carousel simple and clean.

To Reproduce

Go to https://www.linxtion.com/demo/react-image-gallery/
Optional: Disable the navigation , thumbnail and bullets
Play the first slide, it plays a YouTube video
Try to swipe left or right
Not able to slide.
Expected behavior
We should be able to slide even when a video is playing and see the next slide.

Smartphone (please complete the following information):

Device: Realme 2 pro
OS: Android 10
Browser : chrome

Much needed fix.

**Comment by xiaolin** [comment]
Videos are not officially supported and is meant to be an example of what you can do with `renderItem`. Videos embeds will take over the touch actions as it needs priority over its own control (play, pause, etc...). You can look into ways around it or in the example, show a "close" button so that it goes back to the original frame before it can be swiped.
