### ISSUE TITLE
Passive touch events?

### ISSUE THREAD

**Issue by kurtextrem** [xiaolin/react-image-gallery#630]
**Is your feature request related to a problem? Please describe.**
Chrome logs the following when adding non-passive touch listeners to the document:
`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

**Describe the solution you'd like**
`preventDefaultTouchmoveEvent: false` as option passed to react-swipeable: https://www.npmjs.com/package/react-swipeable#:~:text=to%20test%20preventDefaultTouchmoveEvent.-,passive%20listener,-With%20v6%20we%27ve.
This goes hand in hand with: https://www.npmjs.com/package/react-swipeable#how-to-use-touch-action-to-prevent-scrolling

**Describe alternatives you've considered**
There are none.

**Comment by xiaolin** [comment]
Please update bug report with the format below.

**Describe the bug**
A clear and concise description of what the bug is.

**Image Gallery Version**
What version of `react-image-gallery` are you using?

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by kurtextrem** [comment]
Hi, this is not a bug report but a feature request.

**Comment by xiaolin** [comment]
closing as cleaning up, feel free to reopen if this is still an issue.
