### ISSUE TITLE
React 18 Typescript Issue

### ISSUE THREAD

**Issue by dheuermann** [xiaolin/react-image-gallery#728]
Describe the bug
I am trying to upgrade a project to use latest react version 18. I am unable to build the project with typescript due to a compile error, which I believe is related to a type mismatch between @types/react-dom and react-image-gallery:

'ImageGallery' cannot be used as a JSX component.
  Its instance type 'ReactImageGallery' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("/Users/andrew/Projects/example/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.ts(2786)
Image Gallery Version

"react-image-gallery": "1.2.11",
**To Reproduce**

Create a typescript react project with react at version 18.2.0, react-dom at version 18.2.0, @types/react at version 18.2.0, @types/react-dom at version 18.2.0, and react-image-gallery at version 1.2.11.
Create a component that uses the ImageGallery component from react-image-gallery.
Try to build your project with typescript.
See error
**Expected behavior**
I expected that this project would be able to compile using typescript.

**Comment by SajeelHussain** [comment]
You can try casting the ReactImage Gallery to the JSX.element, it may resolve the type mismatch as follows:                                    import React from 'react';
import ImageGallery, { ReactImageGalleryItem } from 'react-image-gallery';

interface ProjectComponentProps {
  images: ReactImageGalleryItem[];
}

const MyComponent: React.FC<ProjectComponentProps> = ({ images }) => {
  return (
    <div>
      {(ImageGallery as any)(images)} // cast ImageGallery to JSX.Element
    </div>
  );
};

export default MyComponent;                                                                                                                                                                Or try updating the verison of your react

**Comment by TechNinja57** [comment]
The error message you are getting is because the ImageGallery component from react-image-gallery is not compatible with React 18. The ImageGallery component is not compatible with React 18 because it uses some features that are no longer supported in React 18.

To fix the error, you need to update the ImageGallery component to a version that is compatible with React 18. You can do this by installing the latest version of the component from npm.

**npm install react-image-gallery@latest**

Once you have installed the latest version of the component, you should be able to build your project with TypeScript without any errors.

If you are still getting errors, you can try downgrading React to a version that is compatible with the ImageGallery component. You can do this by setting the React version in your package.json file.

**"react": "^17.0.2"**

Once you have downgraded React, you should be able to build your project with TypeScript without any errors.

**Comment by xiaolin** [comment]
You should be able to use this lib with your typescript application. TypeScript supports interoperability with JavaScript code, allowing you to use JavaScript libraries seamlessly.
