### ISSUE TITLE
Router support?

### ISSUE THREAD

**Issue by oyeanuj** [xiaolin/react-image-gallery#73]
Hi @xiaolin! Thank you for the component?

I am wondering what your thoughts are on adding router support, i.e. updating the url when navigating left to right?

**Comment by xiaolin** [comment]
I'm not sure what the use case would be for adding a left/right to the route. Can you give me an example of how you would use it?

**Comment by hibearpanda** [comment]
I was actually wondering about this as well - although I'm trying to see if I can hack this together with react router and this package as it currently stands

The use case is basically like facebook or pinterest - click on an image will launch a modal with the image gallery, and navigation to view the rest of the images of an album. The url changes as you navigate the album so that you can share the link to that specific image.

So for example going to this link https://www.facebook.com/hkunhcr/photos/pcb.1271253319559396/1271252956226099/?type=3&theater

will launch a modal with that specific image.

**Comment by xiaolin** [comment]
@hibearpanda Ah, that makes sense. But it would be pretty easy to integrate this package with react-router. You can simply route to your image id, and pass in prop `startIndex` and the ImageGallery will start at the right image.

**Comment by hibearpanda** [comment]
@xiaolin Thanks dude! I'm just finishing up the setup with react-router and the rendering logic, about to try using this package.

keep up the good work - looks fantastic so far

**Comment by xiaolin** [comment]
@oyeanuj I don't think adding router support is a good idea for a standalone component like this. Let me know your thoughts if you disagree.

**Comment by xiaolin** [comment]
Closing this, feel free to reopen if you disagree.
